### ISSUE TITLE
サーバーサイドベースコード

### ISSUE THREAD

**Issue by pei0804** [misoten-iw-g2/lovechan#6]

**Comment by pei0804** [comment]
GAE GoをDockerでやるべきか否か

**Comment by pei0804** [comment]
http://takaya030.hatenablog.com/entry/2017/07/08/181136

**Comment by sr1994lu** [comment]
イメージで喋るけど

[GAE で秘匿したい環境変数を安全に設定する](https://qiita.com/nirasan/items/9527ffa7d2f2fac2933e)

良さそうだけど、docker versionとかdepとか合わせれるの？

合わないんだったらDockerfileかDocker-compose.ymlに書くイメージ。

**Comment by pei0804** [comment]
> GAE で秘匿したい環境変数を安全に設定する

このやり方は出来るよ。ただ、なんかフロントの方でここで設定した環境変数が見れるのか少し謎なんよなー。フロント側で秘匿した情報をどうするか悩ましい。

もし、環境変数が参照出来ない場合に有力なのはAWSでいうS3的なやつのCloud Storageを使って、本番ではそっちを参照するようにする。
[Upload Images to Google Cloud Storage with React Native and ExpressJS](https://medium.com/google-cloud/upload-images-to-google-cloud-storage-with-react-native-and-expressjs-61b8874abc49)

**Comment by pei0804** [comment]
開発スタイルとしては、普段はフロントはnpm startで自由に開発して、APIを叩くためだけに、サーバーサイドを別で立ち上げて開発するってスタイルになるかな。それのが、GAEの制約を気にせず開発することは出来る。

**Comment by pei0804** [comment]
Cloud Storageの仕様が若干だるいから、そこだけ解説する必要あるかなとは思ってる。
一旦はそこらへん気にせずベースを作ってほしい。

ちなみに、必要なことは、ローカルではローカルの設定ファイルを参照するようにして、本番ではCloud Storageを見るように分岐するってことになるかな。

**Comment by sr1994lu** [comment]
あー。Node.js立ち上げてくれるなら出来る想定。やってみないとわからないけど。

**Comment by sr1994lu** [comment]
Node立ち上がってるコンテナ生やしてね

**Comment by pei0804** [comment]
おれも今まであまりフロントでtoken必要になるってケースやったことないから、どうするべきか謎。

**Comment by sr1994lu** [comment]
Node.js立ち上げ時に環境変数をつけて、参照するイメージ。

**Comment by pei0804** [comment]
んー、正直よくわからん。
NodeとGoどっちも立ち上げるのが、果たして正解なのか？って感じがある。

**Comment by pei0804** [comment]
秘匿するべきデータをそもそもフロントで持つべきなのかってのが、そこから間違ってる気がしてる。なんかいい方法ある気がする。

**Comment by sr1994lu** [comment]
そっちで[cognito](https://aws.amazon.com/jp/cognito/)みたいなソリューションないの？

**Comment by pei0804** [comment]
ちなみに、React + Goで開発してるやつで、環境変数参照出来ない時は、以下のやり方で対応してるよ。
[Why I love Create React App – Valerii Sorokobatko – Medium](https://medium.com/@tuchk4/why-i-love-create-react-app-e63b1be689a3)

**Comment by sr1994lu** [comment]
つまり.env金曜日に喋ってたアレ。

**Comment by pei0804** [comment]
それそれ

**Comment by pei0804** [comment]
ただ、本番用に.envをどうやって容易するかちょい考えたい感がある

**Comment by sr1994lu** [comment]
部分SSR(めんどい)するか完全SSR(めんどい)するかNodeランタイム立ち上げて環境変数保持するか

**Comment by pei0804** [comment]
まあ、もうちょい時間頂戴。他の部分先にやってほしい。いま他にタスクがあって出来ないｗ

**Comment by sr1994lu** [comment]
問題なし。楽しもう。

**Comment by pei0804** [comment]
もし、録音した音声をフロントからサーバーに投げる方法があれば秘匿情報をフロントに一切残さず、いい感じにやり取りはできるけどね。

**Comment by pei0804** [comment]
OAuthもそういう感じってわけじゃないけど、似たような構成でやった時は、秘匿情報はフロントに一切漏らさずやってるから、そうした方がアーキテクチャ的には安全で良い感じはある。なんか、わかるなら情報頂戴。

**Comment by sr1994lu** [comment]
![2017-09-30_23-20-08](https://user-images.githubusercontent.com/17734462/31046596-20101ad6-a636-11e7-89e5-7b7aaa58f527.png)

**Comment by pei0804** [comment]
あーなるほど。ちょい調べてみる。

**Comment by pei0804** [comment]
ひとつ思ったのが、これ以外にもやるべきタスクやストーリーがたくさんあるから、これ後回しにして完成急いだほうがいいかもな。

**Comment by pei0804** [comment]
他のが予想以上に進捗よかったらやるとか

**Comment by sr1994lu** [comment]
両方って認識で構成書いちゃうからインフラもそうだし、画面もそう。どのように振る舞うかも書くから、空想にならないように適宜調査は必要だね。

**Comment by pei0804** [comment]
出来ることと出来ないことは調べたほうがよさそうやね。

**Comment by sr1994lu** [comment]
その結果を俺たちは書く。

**Comment by pei0804** [comment]
Reactの.envを使って環境変数でやることにしよう。
どうするかは、CIのデプロイフェーズでファイルをぶち込むロジック入れるようにする。
※検証が終わったら再度言う。それまでは保留で！

**Comment by sr1994lu** [comment]
その認識ならリポジトリをprivateにしてもらって、webpackにdevとprodで書き換えるよ。

**Comment by pei0804** [comment]
おれの考えたプランとしては、タスク中に.envを作成して、その.envを元にbuildしてdeployするって感じでいける。

**Comment by pei0804** [comment]
> その認識ならリポジトリをprivateにしてもらって、webpackにdevとprodで書き換えるよ。

CIでどうにか出来る領域だから、大丈夫よ！

**Comment by pei0804** [comment]
というより、privateにしないと安全なリポジトリに出来ないってのがあまり好きではない。

**Comment by pei0804** [comment]
https://github.com/wercker/step-create-file
こういうのがあるからいけるよ。
あとはファイル作成時に秘匿すべきとこは全部Weckerの環境変数に置き換えれば、どこにもtoken情報残さず運用出来る。

**Comment by sr1994lu** [comment]
開発時どうする？

**Comment by pei0804** [comment]
開発時は、.env.devみたいな.envを参照する形で実行してほしい。

**Comment by sr1994lu** [comment]
あーその中身教えてくれる？

**Comment by pei0804** [comment]
いま、どんな値を用意するべきか予想出来ないから、それっぽい変数名とそれっぽい値だけ用意するね。

```
REACT_APP_API_SCHEME = http://
REACT_APP_API_HOST = localhost:8080
REACT_APP_SPEECH_TOKEN = "1087678318033574"
```

**Comment by sr1994lu** [comment]
デプロイ時にさ、環境変数から値を埋め込むシェルスクリプト書いてほしいのが本音どう？

**Comment by pei0804** [comment]
> 環境変数から値を埋め込むシェルスクリプト書いてほしいのが本音どう？

どういうこと？そこらへんの作業をやってほしいってこと？

**Comment by sr1994lu** [comment]
http://itpro.nikkeibp.co.jp/article/COLUMN/20060227/230879/?rt=nocnt

**Comment by pei0804** [comment]
sedありやな。

**Comment by sr1994lu** [comment]
`API_Scheme=3000 API_Host=... node app.js`

**Comment by pei0804** [comment]
なんか良い書き方があるなら、それでいいよ。
あとで、その.envを教えてくれればおｋ！

**Comment by sr1994lu** [comment]
ファイルいらなくてデプロイ時にこう書いて走らせてってこと！

**Comment by pei0804** [comment]
あーなるほど

**Comment by sr1994lu** [comment]
機密データはサーバ上のランタイム担保

**Comment by sr1994lu** [comment]
package.jsonのscriptsにはbashから環境変数取得したらええやろ

**Comment by pei0804** [comment]
そっちが都合良い書き方あるならそれでやっていいよ。
後で、どうするべきかを教えてくれたらタスク作る。

**Comment by sr1994lu** [comment]
デプロイ日時をasanaで立てて。
デプロイ走らせるマイルストーン置いてくれたらそれに合わせてスケジューリングする。
ci時に走らせるコマンドも明示してasanaにコメントしておく。

**Comment by pei0804** [comment]
おｋ
とりあえず、月曜日になるまで自由がないから、それまで待ってもらってよい？

**Comment by sr1994lu** [comment]
.envとか使うとブラウザに環境変数を永続化させて心臓に悪い。

**Comment by sr1994lu** [comment]
いつでもどうぞ！

**Comment by sr1994lu** [comment]
asanaにfrontとserverのタスク存在してる。進捗やスケジューリングを考える見るときはinstagantで。

**Comment by sr1994lu** [comment]
instagantのcreate group of projectsでfrontとserverのガントチャートを結合できるのでおすすめ。
